name: flutter_application_stage_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  flutter_otp_text_field: ^1.1.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  language_code: ^0.5.3+2
  chat_bubbles: ^1.5.0
  percent_indicator: ^4.2.3
  file_picker: ^8.1.2
  table_calendar: ^3.0.9
  day_night_time_picker: ^1.3.0+1
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.14
  timelines: ^0.1.0
  image_picker: ^1.0.7
  appflowy_board: ^0.1.1
  drag_and_drop_lists: ^0.4.1
  floating_action_bubble: ^1.1.4
  flutter_localization: ^0.2.0
  fl_chart: ^0.35.0
  http: ^1.2.2 # Rétrogradé pour être compatible avec mercure_client
  omni_datetime_picker: ^1.0.9
  flutter_rating_bar: ^4.0.1
  dio: ^5.4.3+1
  multi_select_flutter: ^4.1.3
  flutter_form_builder: ^9.2.0
  flutter_slidable: ^3.1.0
  intl_phone_field: ^3.2.0
  flutter_spinkit: ^5.2.1
  flutter_charts: ^0.5.2
  syncfusion_flutter_charts: ^26.2.10
  web_socket_channel: ^3.0.1
  mercure_client: ^1.0.0 # Version compatible avec http ^0.13.3
  flutter_local_notifications: ^17.1.3
  permission_handler: ^11.0.1
  infinite_scroll_pagination: ^4.0.0
  device_preview: ^1.1.0
  html: ^0.15.4
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.9.0
  flutter_quill: ^10.7.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_comunik.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: ProstoOne
      fonts:
        - asset: assets/fonts/ProstoOne/ProstoOne-Regular.ttf
        # Add other font weights/styles if available
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
        # Add other font weights/styles if available
