// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_jtSQvLBluB2bkRhRJWhqj8-bKWSSH0o',
    appId: '1:554727672198:web:e4a47fd7d022a4a6d84407',
    messagingSenderId: '554727672198',
    projectId: 'samer-fcm',
    authDomain: 'samer-fcm.firebaseapp.com',
    storageBucket: 'samer-fcm.firebasestorage.app',
    measurementId: 'G-1EFYFKPEZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLT1OZwvJtOI-s4_WTixBZvzAq45MsGHM',
    appId: '1:554727672198:android:d96eadc3e35ead98d84407',
    messagingSenderId: '554727672198',
    projectId: 'samer-fcm',
    storageBucket: 'samer-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_AI3hAbJWMaVntuMNQ-v03mWEHJF7wpY',
    appId: '1:554727672198:ios:d424f26030988036d84407',
    messagingSenderId: '554727672198',
    projectId: 'samer-fcm',
    storageBucket: 'samer-fcm.firebasestorage.app',
    iosBundleId: 'com.comunikcrm.sphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_AI3hAbJWMaVntuMNQ-v03mWEHJF7wpY',
    appId: '1:554727672198:ios:a4eedce6892d193bd84407',
    messagingSenderId: '554727672198',
    projectId: 'samer-fcm',
    storageBucket: 'samer-fcm.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationStageProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_jtSQvLBluB2bkRhRJWhqj8-bKWSSH0o',
    appId: '1:554727672198:web:8e1c60ed04688f2ad84407',
    messagingSenderId: '554727672198',
    projectId: 'samer-fcm',
    authDomain: 'samer-fcm.firebaseapp.com',
    storageBucket: 'samer-fcm.firebasestorage.app',
    measurementId: 'G-L0R6FG5L6R',
  );
}